Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [7]:
import numpy as np

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1,3,5],[2,4,6]])
vert = np.vstack((A, B))
hori = np.hstack((A, B))

In [12]:
print(vert, hori)

[[1 2 3]
 [4 5 6]
 [1 3 5]
 [2 4 6]] [[1 2 3 1 3 5]
 [4 5 6 2 4 6]]
