Q1: Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [7]:
import numpy as np

In [15]:
A = np.array([1,2,3,4,5])
B = np.array([1,3,5,7,9])
vert = np.vstack((A, B))
hori = np.hstack((A, B))

In [16]:
print(vert, hori)

[[1 2 3 4 5]
 [1 3 5 7 9]] [1 2 3 4 5 1 3 5 7 9]


Q2: Find common elements between A and B. [Hint : Intersection of two sets]

In [18]:
intersection = np.intersect1d(A,B)
print(intersection)

[1 3 5]


Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [31]:
rangein = np.where((A>=2) & (A<=4))

In [32]:
A[rangein]

array([2, 3, 4])