Create a 4x4 NumPy array filled with random integers between 1 and 100. Then, reshape this array into two separate 2D arrays, where one represents the rows and the other represents the columns. Write a function, preferably using a lambda function, to calculate the sum of each row and each column separately, and return the results as two separate NumPy arrays

In [1]:
import numpy as np

In [3]:
array = np.random.randint(1,101,(4,4))
print(array)

[[ 97  14  60  76]
 [  4  45  21  28]
 [ 30  43  61  67]
 [100  46   8  15]]


In [7]:
rows = array.reshape(2,8)
columns = array.reshape(8,2)
print(rows, columns)

[[ 97  14  60  76   4  45  21  28]
 [ 30  43  61  67 100  46   8  15]] [[ 97  14]
 [ 60  76]
 [  4  45]
 [ 21  28]
 [ 30  43]
 [ 61  67]
 [100  46]
 [  8  15]]


In [8]:
sum_row = lambda array: np.sum(array, axis=1)
sum_column = lambda array: np.sum(array, axis=0)

In [9]:
sum_rows_result = sum_row(rows)
sum_columns_result = sum_column(columns)

In [10]:
print(sum_rows_result, sum_columns_result)

[345 370] [381 334]
